
CREATE TABLE SOCIO
(
	RUC                  VARCHAR2(15) NULL ,
	NOMBRE               VARCHAR2(50) NOT NULL ,
	APELLIDO             VARCHAR2(50) NULL ,
	FECHA_NACIMIENTO     DATE NOT NULL ,
	DIRECCION            VARCHAR2(60) NOT NULL ,
	TELEFONO             VARCHAR2(20) NOT NULL ,
	CEDULA               VARCHAR2(12) NOT NULL ,
	CORREO_ELECTRONICO   VARCHAR2(40) NOT NULL ,
	SUSCRIPTO_MAIL       VARCHAR2(1) NOT NULL ,
	FECHA_BAJA           DATE NULL ,
	MOTIVO_BAJA          VARCHAR2(40) NULL ,
	FIRMA                BLOB NULL ,
	ID_SOCIO             NUMBER(12) NOT NULL ,
	FECHA_INGRESO        DATE NOT NULL ,
CONSTRAINT  PKSOCIO PRIMARY KEY (ID_SOCIO)
);

CREATE TABLE APORTES
(
	ID_SOCIO             NUMBER(12) NULL ,
        MONTO_APORTE         NUMBER(9) DEFAULT  0  NOT NULL ,
	FECHA_APORTE         DATE NOT NULL ,
	NRO_BOLETA           NUMBER(12) NOT NULL ,
CONSTRAINT  PKAPORTES PRIMARY KEY (NRO_BOLETA)
);

CREATE TABLE CONCEPTOS
(
	ID_CONCEPTO          NUMBER(2) NOT NULL ,
	NOMBRE_CONCEPTO      VARCHAR2(30) NOT NULL ,
	INGRESO_GASTO        VARCHAR(1) DEFAULT  'I'  NULL  CONSTRAINT  CHK_ING_GAS CHECK (INGRESO_GASTO IN ('I','G')),
CONSTRAINT  PKCONCEPTOS PRIMARY KEY (ID_CONCEPTO)
);

CREATE TABLE INGRESOS_Y_GASTOS
(       ID                   NUMBER(10),
	FECHA_DECLARACION    DATE NOT NULL ,
	ID_SOCIO             NUMBER(12) NOT NULL ,
	IMPORTE              NUMBER(15) NOT NULL ,
	ID_CONCEPTO          NUMBER(2) NOT NULL ,
CONSTRAINT  PKDECLARACION PRIMARY KEY (ID, FECHA_DECLARACION,ID_SOCIO)
);

CREATE TABLE INMUEBLES
(
	ID                   NUMBER(8) NOT NULL ,
	ID_SOCIO             NUMBER(12) NULL ,
	CTA_CTE_CATASTRAL    VARCHAR2(20) NOT NULL ,
	FINCA                VARCHAR2(15) NOT NULL ,
	SUPERFICIE_M2        NUMBER(4) NOT NULL ,
	VALOR_FISCAL         NUMBER(15) NOT NULL ,
	VALOR_AVALUO         NUMBER(15) NULL ,
CONSTRAINT  PKINMUEBLES PRIMARY KEY (ID)
);

CREATE TABLE PRESTAMOS
(
	NRO_PRESTAMO         NUMBER(8) NOT NULL ,
	ID_SOCIO             NUMBER(12) NULL ,
	CODIGO_TIPO          NUMBER(2) NULL ,
	FECHA_PRESTAMO       DATE DEFAULT  SYSDATE  NOT NULL ,
	MONTO_PRESTAMO       NUMBER(9) DEFAULT  0  NOT NULL ,
	PLAZO_EN_MESES       NUMBER(2) DEFAULT  12  NOT NULL ,
	FECHA_CANCEL         DATE,
	TIPO_CANCEL          VARCHAR2(1) NULL  CONSTRAINT  TIPO_CANCELACION4 CHECK (TIPO_CANCEL IN ('N', 'C', 'R')),
CONSTRAINT  PKPRESTAMOS PRIMARY KEY (NRO_PRESTAMO)
);

CREATE TABLE CUOTAS
(
	NRO_PRESTAMO         NUMBER(8) NOT NULL ,
	NRO_CUOTA            NUMBER(8) NOT NULL ,
	AMORTIZACION         NUMBER(15) DEFAULT  0  NOT NULL ,
	MONTO_CUOTA          NUMBER(15) NOT NULL ,
	INTERES              NUMBER(15) NULL ,
	IVA                  NUMBER(15) NOT NULL, 
	FECHA_VENCIM         DATE DEFAULT  SYSDATE  NOT NULL ,
	FECHA_PAGO           DATE,
	MORA_CALCULADA       NUMBER(15) DEFAULT  0  NULL ,
CONSTRAINT  PKCUOTAS PRIMARY KEY (NRO_PRESTAMO,NRO_CUOTA)
);

CREATE TABLE RODADOS
(
	RUA                  VARCHAR2(30) NOT NULL ,
	ID_SOCIO             NUMBER(12) NULL ,
	TIPO_VEHICULO        VARCHAR2(20) NOT NULL ,
	MARCA                VARCHAR2(25) NOT NULL ,
	MODELO               VARCHAR2(25) NOT NULL ,
	VALOR                NUMBER(12) NOT NULL ,
CONSTRAINT  PKRODADOS PRIMARY KEY (RUA)
);

CREATE TABLE CUENTAS
(
	ID_CUENTA            VARCHAR2(20) NOT NULL ,
	ID_SOCIO             NUMBER(12) NULL ,
	NOMBRE_CUENTA        VARCHAR(50) NOT NULL ,
	TIPO_CUENTA          VARCHAR2(1) NOT NULL ,
	DEBITOS              NUMBER(15) NOT NULL ,
	CREDITOS             NUMBER(15) NOT NULL ,
CONSTRAINT  PKCUENTAS_CTES PRIMARY KEY (ID_CUENTA)
);

CREATE TABLE EVENTOS
(
	COD_EVENTO           NUMBER(2) NOT NULL ,
	NOMBRE_EVENTO        VARCHAR2(40) NOT NULL ,
	MONTO_COBERTURA      NUMBER(10) DEFAULT 0 NOT NULL ,
	UNIDAD_TIEMPO        VARCHAR2(20) DEFAULT 'D' NOT NULL CONSTRAINT CHK_UNI 
        CHECK (UNIDAD_TIEMPO IN ('E','D')) ,
CONSTRAINT  PKEVENTOS PRIMARY KEY (COD_EVENTO)
);

CREATE TABLE SOLICITUD_PREMIOS
(
	ID_SOCIO             NUMBER(12) NOT NULL ,
	COD_EVENTO           NUMBER(2) NULL ,
	FECHA_DESDE          DATE NOT NULL ,
	FECHA_HASTA          DATE NULL ,
	FECHA_PRESENTACION   DATE NOT NULL ,
	CONCEDIDO            VARCHAR(1) NULL,
	ID                   NUMBER(10) NOT NULL ,
CONSTRAINT  PKSOLICITUD_PREMIOS PRIMARY KEY (ID)
);

CREATE TABLE PARAMETROS
(
	MONTO_APORTE_ANUAL   NUMBER(8) NULL ,
	ANTIGUEDAD_MINIMA    NUMBER(2) NOT NULL ,
	RUC_COOPERATIVA      VARCHAR(15) NOT NULL ,
	INTERES_MORATORIO_BCP NUMBER(2) NULL 
);

CREATE TABLE TIPO_MOVIMIENTO
(
	ID_TIPO              NUMBER(2) NOT NULL ,
	NOMBRE_TIPO          VARCHAR2(20) NOT NULL ,
	DEBITO_CREDITO       VARCHAR2(1) DEFAULT  'D'  NOT NULL  CONSTRAINT  CHK_DEB_CRED CHECK (DEBITO_CREDITO IN ('D','C')),
CONSTRAINT  PKTIPO_MOVIMIENTO PRIMARY KEY (ID_TIPO)
);

CREATE TABLE MOVIMIENTO_CUENTAS
(
	ID_MOVIMIENTO        NUMBER(12) NOT NULL ,
	FECHA_MOVIM          DATE NULL ,
	CHEQUE_NRO           VARCHAR2(20) NULL ,
	IMPORTE              NUMBER(15) NULL ,
	ID_CUENTA            VARCHAR2(20) NOT NULL ,
	ID_TIPO              NUMBER(2) NULL ,
CONSTRAINT  PKMOVIMIENTO_CUENTAS PRIMARY KEY (ID_MOVIMIENTO,ID_CUENTA)
);

CREATE TABLE TIPO_PRESTAMO
(
	NOMBRE_TIPO          VARCHAR2(60) NOT NULL ,
	TASA_INTERES_ANUAL   NUMBER(2) NOT NULL ,
	RELACION_APORTES     NUMBER(2) NOT NULL ,
	CODIGO_TIPO          NUMBER(2) NOT NULL ,
	PLAZO_MAXIMO         NUMBER(2) NOT NULL ,
CONSTRAINT  PKTIPO_PRESTAMO PRIMARY KEY (CODIGO_TIPO)
);

ALTER TABLE APORTES
	ADD (CONSTRAINT R_SOCIO_APORTE FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO (ID_SOCIO));

ALTER TABLE INGRESOS_Y_GASTOS
	ADD (CONSTRAINT R_CONCEPTO_DECLAR FOREIGN KEY (ID_CONCEPTO) REFERENCES CONCEPTOS (ID_CONCEPTO));

ALTER TABLE INGRESOS_Y_GASTOS
	ADD (CONSTRAINT R_SOCIO_DECLA FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO (ID_SOCIO));

ALTER TABLE INMUEBLES
	ADD (CONSTRAINT R_SOCIO_INMUEB FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO (ID_SOCIO));

ALTER TABLE PRESTAMOS
	ADD (CONSTRAINT R_SOCIO_PRESTA FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO (ID_SOCIO));

ALTER TABLE PRESTAMOS
	ADD (CONSTRAINT R_TIPO_PRESTA FOREIGN KEY (CODIGO_TIPO) REFERENCES TIPO_PRESTAMO (CODIGO_TIPO));

ALTER TABLE CUOTAS
	ADD (CONSTRAINT R_PRESTAMO_CUOTA FOREIGN KEY (NRO_PRESTAMO) REFERENCES PRESTAMOS (NRO_PRESTAMO));

ALTER TABLE RODADOS
	ADD (CONSTRAINT R_SOCIO_RODADOS FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO (ID_SOCIO));

ALTER TABLE CUENTAS
	ADD (CONSTRAINT R_SOCIO_CUENTAS FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO (ID_SOCIO));

ALTER TABLE SOLICITUD_PREMIOS
	ADD (CONSTRAINT R_SOCIO_PREMIO FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO (ID_SOCIO));

ALTER TABLE SOLICITUD_PREMIOS
	ADD (CONSTRAINT R_EVENTO_PREMIO FOREIGN KEY (COD_EVENTO) REFERENCES EVENTOS (COD_EVENTO));

ALTER TABLE MOVIMIENTO_CUENTAS
	ADD (CONSTRAINT R_CTA_MOVIM FOREIGN KEY (ID_CUENTA) REFERENCES CUENTAS (ID_CUENTA));

ALTER TABLE MOVIMIENTO_CUENTAS
	ADD (CONSTRAINT R_TIPO_MOVIM FOREIGN KEY (ID_TIPO) REFERENCES TIPO_MOVIMIENTO (ID_TIPO));
