CREATE DATABASE TEST1;
USE TEST1;

DROP DATABASE TEST1

START TRANSACTION;

CREATE TABLE MATERIAS
(
  ID_MATERIA NUMBER(5) NOT NULL,
  NOMBRE_MATERIA VARCHAR2(45) NOT NULL,
  COSTO_MATERIA NUMBER(7) NOT NULL,
  CONSTRAINT ID_MATERIA_PK PRIMARY KEY ( ID_MATERIA )
)

CREATE TABLE CARRERAS
(
  ID_CARRERA NUMBER(5) NOT NULL,
  NOMBRE_CARRERA VARCHAR2(30) NOT NULL,
  TOTAL_HORAS NUMBER(2) NOT NULL,
  TITULO_HABILITANTE VARCHAR2(30) NOT NULL,
  FECHA_HABILITACION DATE NOT NULL,
  FECHA_CANCELACION DATE NULL,
  CONSTRAINT ID_CARRERA_PK PRIMARY KEY( ID_CARRERA )
)

CREATE TABLE PROFESORES
(

  PROFESOR NUMBER(4) NOT NULL,
  NOMBRE_PROFESOR VARCHAR2(60) NOT NULL,
  DIRECCION_PROFESOR VARCHAR2(45) NOT NULL,
  TELEFONO_PROFESOR VARCHAR2(15) NOT NULL,
  E_MAIL_PROFESOR VARCHAR2(30) NULL,
  CONSTRAINT PROFESOR_PK PRIMARY KEY( PROFESOR )

)

CREATE TABLE PROGRAMA_CURRICULAR
(
  ID_MATERIA NUMBER(5) NOT NULL,
  ID_CARRERA NUMBER(5) NOT NULL,
  ELECTIVA VARCHAR2(1) NOT NULL,
  CARGA_HORARIA NUMBER(1) NOT NULL,
  CANT_CREDITOS NUMBER(2) NOT NULL,
  CONSTRAINT ID_MATERIA_FK
    FOREIGN KEY( ID_MATERIA )
    REFERENCES MATERIAS( ID_MATERIA ),
  CONSTRAINT ID_CARRERA_FK
    FOREIGN KEY( ID_CARRERA )
    REFERENCES CARRERAS( ID_CARRERA )

)

CREATE TABLE MATERIA_SECCION
(

  ID_CARRERA NUMBER(5) NOT NULL,
  ID_MATERIA NUMBER(5) NOT NULL,
  SECCION VARCHAR2(1) NOT NULL,
  PROFESOR NUMBER(4) NULL,
  CONSTRAINT PROFESOR_FK
    FOREIGN KEY( PROFESOR )
    REFERENCES PROFESORES( PROFESOR ),
  CONSTRAINT ID_CARRERA_FK
    FOREIGN KEY( ID_CARRERA )
    REFERENCES PROGRAMA_CURRICULAR( ID_CARRERA ),
  CONSTRAINT ID_MATERIA_FK
    FOREIGN KEY( ID_MATERIA )
    REFERENCES PROGRAMA_CURRICULAR( ID_MATERIA )

)

CREATE TABLE ESTUDIANTES
(

  CEDULA NUMBER(8) NOT NULL,
  NOMBRE VARCHAR2(45) NOT NULL,
  DIRECCION VARCHAR2(45) NOT NULL,
  APELLIDO VARCHAR2(45) NOT NULL,
  TELEFONO VARCHAR2(15) NOT NULL,
  TELEFONO_TRABAJO VARCHAR2(15) NULL,
  DIRECCION_TRABAJO VARCHAR2(45) NULL,
  E_MAIL VARCHAR2(30) NULL,
  FECHA_PRIMERA_INSCRIPCION DATE NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  CONSTRAINT CEDULA_PK PRIMARY KEY(CEDULA)

)

CREATE TABLE MATRICULA
(

  ID_MATRICULA NUMBER(8) NOT NULL,
  CEDULA NUMBER(8) NOT NULL,
  FECHA_INSCRIPCION DATE NOT NULL,
  FECHA_FIN_MATRICULA DATE NULL,
  MOTIVO_CANCELACCION VARCHAR2(1) NULL,
  ID_CARRERA NUMBER(5) NULL,
  ID_MATERIA NUMBER(5) NULL,
  SECCION VARCHAR2(1) NULL,
  CONSTRAINT ID_MATRICULA_PK PRIMARY KEY(ID_MATRICULA),
  CONSTRAINT CEDULA_FK FOREIGN KEY( CEDULA )
    REFERENCES ESTUDIANTES( CEDULA ),
  CONSTRAINT ID_CARRERA_FK FOREIGN KEY( ID_CARRERA )
    REFERENCES CARRERAS( ID_CARRERA ),
  CONSTRAINT ID_MATERIA_FK FOREIGN KEY( ID_MATERIA )
    REFERENCES MATERIAS( ID_MATERIA ),
  CONSTRAINT SECCION_PK FOREIGN KEY( SECCION )
    REFERENCES MATERIA_SECCION( SECCION )
)

CREATE TABLE ACTA
(

  NUMERO_ACTA NUMBER(8) NOT NULL,
  FECHA_ACTA DATE NOT NULL,
  TIPO_EXAMEN VARCHAR2(5) NOT NULL,
  CONSTRAINT ACTA_PK PRIMARY KEY( NUMERO_ACTA )

)

CREATE TABLE CALIFICACIONES
(
  ID_MATRICULA NUMBER(8) NOT NULL,
  NUMERO_ACTA NUMBER(8) NOT NULL,
  PUNTAJE NUMBER(3) NOT NULL,
  CONSTRAINT CALIFICACIONES_PK PRIMARY KEY ( ID_MATRICULA, NUMERO_ACTA ),
  CONSTRAINT ID_MATRICULA_FK FOREIGN KEY ( ID_MATRICULA )
    REFERENCES MATRICULA( ID_MATRICULA ),
  CONSTRAINT NUMERO_ACTA_FK FOREIGN KEY( NUMERO_ACTA )
    REFERENCES ACTA( NUMERO_ACTA )
)

COMMIT
