CREATE OR REPLACE PACKAGE PACK_PER IS 
	TYPE R_EMP IS RECORD 
		(MONTO_VENTAS B_VENTAS.MONTO_TOTAL%TYPE,
		 MONTO_COMISION B_VENTAS.MONTO_TOTAL%TYPE
		 );
	TYPE T_EMP IS TABLE OF R_EMP 
		INDEX BY BINARY_INTEGER;
	V_EMP T_EMP; 
	V_CALCULA_BONIF BOOLEAN :=TRUE;
	FUNCTION F_APELLIDO_NOMBRE(P_CED NUMBER) 
		RETURN VARCHAR2;
	FUNCTION F_CALCULAR_BONIFICACION (P_MES NUMBER, P_ANHO NUMBER)
		RETURN T_EMP;
	FUNCTION F_CALCULAR_BONIFICACION (P_CED NUMBER)
		RETURN NUMBER;
END;	

CREATE OR REPLACE PACKAGE BODY PACK_PER IS 
    VAR NUMBER;
	FUNCTION F_APELLIDO_NOMBRE(P_CED NUMBER) RETURN VARCHAR2 IS
		V_NOMBRE VARCHAR2(400);
		V_ERROR EXCEPTION;
		BEGIN
			SELECT E.APELLIDO||', '||E.NOMBRE INTO V_NOMBRE
				FROM B_EMPLEADOS E
				WHERE E.CEDULA = P_CED;
			IF V_NOMBRE IS NULL THEN
				RAISE V_ERROR;
			ELSE 
				RETURN V_NOMBRE;
			END IF;
			
		EXCEPTION 
			WHEN V_ERROR THEN 
				V_NOMBRE:='N/A';
				RETURN V_NOMBRE; 
			WHEN NO_DATA_FOUND THEN
				V_NOMBRE:='N/A';
				RETURN V_NOMBRE;
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20001,'ERROR AL BUSCAR EL NOMBRE');
		END;
	FUNCTION F_CALCULAR_BONIFICACION (P_MES NUMBER, P_ANHO NUMBER)
		RETURN T_EMP IS 
			CURSOR C_EMP IS 
				SELECT E.CEDULA, 
					SUM(DV.PRECIO*DV.CANTIDAD) MONTO_TOTAL,
					SUM(DV.PRECIO*DV.CANTIDAD*A.PORC_COMISION) MONTO_COMISION 
				FROM B_EMPLEADOS E
					JOIN B_VENTAS V ON E.CEDULA=CEDULA_VENDEDOR
					JOIN B_DETALLE_VENTAS DV ON V.ID=DV.ID_VENTA
					JOIN B_ARTICULOS A ON DV.ID_ARTICULO=A.ID
				WHERE 
						EXTRACT (MONTH FROM V.FECHA)=P_MES
						AND EXTRACT (YEAR FROM V.FECHA)=P_ANHO
				GROUP BY E.CEDULA;
		V_EMP T_EMP;
		BEGIN
			FOR R IN C_EMP LOOP
				V_EMP(R.CEDULA).MONTO_VENTAS:=R.MONTO_TOTAL;
				V_EMP(R.CEDULA).MONTO_COMISION:=R.MONTO_COMISION;
			END LOOP;
			RETURN V_EMP;
		EXCEPTION
			WHEN OTHERS THEN
				RAISE_APPLICATION_ERROR(-20002,'ERROR AL RECUPERAR COMISIONES 1');
		END;
	FUNCTION F_CALCULAR_BONIFICACION (P_CED NUMBER)
		RETURN NUMBER IS
			V_COMISION NUMBER;
			BEGIN 
				SELECT 
					SUM(DV.PRECIO*DV.CANTIDAD*A.PORC_COMISION) 
					INTO V_COMISION
				FROM B_EMPLEADOS E
					JOIN B_VENTAS V ON E.CEDULA=CEDULA_VENDEDOR
					JOIN B_DETALLE_VENTAS DV ON V.ID=DV.ID_VENTA
					JOIN B_ARTICULOS A ON DV.ID_ARTICULO=A.ID
				WHERE 
					E.CEDULA=P_CED;
				Ç+
				
				RET0URN
				URN V_COMISION;
			EXCEPTION
				WHEN OTHERS THEN
					RAISE_APPLICATION_ERROR(-20003,'ERROR AL RECUPERAR COMISION 2');
			END;
END;	
	
	