CREATE OR REPLACE TRIGGER T_VERIF_ASIGNACION
BEFORE INSERT ON B_POSICION_ACTUAL 
FOR EACH ROW
DECLARE	
 V_ASIG_ANT NUMBER;
 V_ASIG_ACT NUMBER;
BEGIN
	SELECT ASIGNACION INTO V_ASIG_ANT
	FROM B_POSICION_ACTUAL PA
	 JOIN B_CATEGORIAS_SALARIALES CS
	  ON PA.COD_CATEGORIA =CS.COD_CATEGORIA
	 WHERE PA.CEDULA = :NEW.CEDULA
	 AND PA.FECHA_INI=(
					 SELECT MAX(FECHA_INI)	FROM B_POSICION_ACTUAL
						WHERE CEDULA = :NEW.CEDULA
					   );
	SELECT  ASIGNACION INTO V_ASIG_ACT
		FROM B_CATEGORIAS_SALARIALES CS
		WHERE COD_CATEGORIA=:NEW.COD_CATEGORIA;
	
	IF V_ASIG_ANT>V_ASIG_ACT THEN
		RAISE_APPLICATION_ERROR(-20004,'ASIGNACION ANTERIOR ES MAYOR A ASIGNACION ACTUAL');	
	END IF;
EXCEPTION 
	WHEN OTHERS THEN
		RAISE_APPLICATION_ERROR(-20004,'SE PRODUJO UN ERROR'||SQLERRM);
END;




-- 








CREATE OR REPLACE TRIGGER T_EVITABORRADO 
BEFORE DELETE ON B_POSICION_ACTUAL 
BEGIN 
	RAISE_APPLICATION_ERROR(-20003,'NO SE PUEDE BORRAR REGISTROS DE ESTA TABLA');
END;
